legacy/ScooterRental/ScooterRental/Models/Monitor.cs
using System;

namespace ScooterRental.Models
{
    public class Monitor
    {
        public Monitor(Scooter scooter, int locationAreaId)
        {
            if(scooter.User?.PassportNumber == null)
            {
                throw new ApplicationException("You cannot monitor an unrented scooter");
            }

            if (locationAreaId <= 0)
            {
                throw new ApplicationException("You cannot monitor without a location area");
            }

            this.Scooter = scooter;
            this.LocationAreaId = locationAreaId;
        }
        public int Id { get; set; }

        public Scooter Scooter { get; private set; }
        public int LocationAreaId { get; private set; }

        public void SetLocationArea(int locationAreaId)
        {
            this.LocationAreaId = locationAreaId;
        }
    }
}

legacy/ScooterRental/ScooterRental/Models/Scooter.cs
using System;

namespace ScooterRental.Models
{
    public class Scooter
    {
        public Scooter(long id, User user = null)
        {
            this.Id = id;
            this.User = user;
        }

        public long Id { get; private set; }
        
        public bool Available => User == null;

        public User User { get; private set; }

        public void Rent(string passport)
        {
            if (this.User?.PassportNumber != null)
            {
                throw new ApplicationException("You cannot rent a rented scooter");
            }

            this.User = new User(passport);
        }
        
        public void TurnBack()
        {
            if (this.User?.PassportNumber == null)
            {
                throw new ApplicationException("You cannot turn back an unrented scooter");
            }

            this.User = null;
        }
    }
}

legacy/ScooterRental/ScooterRental/Models/User.cs
using System;

namespace ScooterRental.Models
{
    public class User
    {
        public User(string PassportNumber)
        {
            if (PassportNumber == null)
            {
                throw new ApplicationException("You cannot have an user without passport number");
            }

            this.PassportNumber = PassportNumber;
        }

        public string PassportNumber { get; private set; }
    }
}

legacy/ScooterRental/ScooterRental/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScooterRental.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Legacy System.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact page.";

            return View();
        }
    }
}

legacy/ScooterRental/ScooterRental/Controllers/ScooterController.cs
using ScooterRental.Dal;
using ScooterRental.Models;

using System;
using System.Web.Mvc;

namespace ScooterRental.Controllers
{
    public class ScooterController : Controller
    {
        private readonly ScooterDal scooterDal;
        private readonly MonitorDal monitorDal;

        public ScooterController()
        {
            this.scooterDal = new ScooterDal();
            this.monitorDal = new MonitorDal();
        }

        public ActionResult Rent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Rent(int scooterId, string passportNumber)
        {
            try
            {
                var scooter = this.scooterDal.Get(scooterId);
                scooter.Rent(passportNumber);

                this.scooterDal.Update(scooter);

                //Monitor
                var locationAreaId = new Random().Next(1, 200);
                monitorDal.Insert(new Monitor(scooter, locationAreaId));

                ViewBag.Alert = "The Scooted Was Rented";
            }
            catch (ApplicationException appEx)
            {
                ViewBag.Alert = appEx.Message;
            }
            return View();
        }

        public ActionResult TurnBack()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TurnBack(int scooterId)
        {
            try
            {
                var scooter = this.scooterDal.Get(scooterId);
                scooter.TurnBack();

                this.scooterDal.Update(scooter);

                //Monitor
                var locationAreaId = new Random().Next(1, 200);
                monitorDal.Insert(new Monitor(scooter, locationAreaId));

                ViewBag.Alert = "The Scooted Was Turned Back";
            }
            catch (ApplicationException appEx)
            {
                ViewBag.Alert = appEx.Message;
            }
            return View();
        }

        public ActionResult Check(int? scooterId = null)
        {
            try
            {
                if (scooterId != null)
                {
                    var monitor = this.monitorDal.GetByScooter(scooterId.GetValueOrDefault());

                    if (monitor == null)
                        ViewBag.Alert = "The Scooted Was Not Rented";

                    return View(monitor);
                }
            }
            catch (ApplicationException appEx)
            {
                ViewBag.Alert = appEx.Message;
            }
            return View();
        }
    }
}

legacy/ScooterRental/ScooterRental/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Scooter Rental System.</p>

legacy/ScooterRental/ScooterRental/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    <a href="https://github.com/andreraica/ScooterRental">André Raiça Silva - GitHub</a>
</address>

<address>
    <strong>Support:</strong>   <a href="https://github.com/andreraica/ScooterRental">Readme</a><br />
</address>

legacy/ScooterRental/ScooterRental/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Scooter Rental";
}

<div class="jumbotron">
    <h1>Scooter Rental System</h1>
    <p class="lead">It is a monolithic legacy system built with MVC, Razor and .net Full Framework.</p>
    <p><a href="https://github.com/andreraica/ScooterRental" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>1. Renting a scooter</h2>
        <p>
            Rent a scooter using your passport number.
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Rent", "Scooter")">Rent Scooter &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>2. Turn back the scooter</h2>
        <p>
            Turn back the scooter that you got.
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("TurnBack", "Scooter")">Turn Back Scooter &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>3. Check Scooters</h2>
        <p>Check the scooter status and localization.</p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Check", "Scooter", 0)">Check Scooter &raquo;</a>
        </p>
    </div>
</div>

legacy/ScooterRental/ScooterRental/Views/Scooter/Check.cshtml
@model ScooterRental.Models.Monitor

@{
    ViewBag.Title = "Check a Scooter";
}
<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Check", "Scooter", FormMethod.Get))
{
    <p>
        Scooter:
        @Html.DropDownList("ScooterId", new List<SelectListItem>
        {
        new SelectListItem{ Text="Scooter 1", Value = "1" },
        new SelectListItem{ Text="Scooter 2", Value = "2" },
        new SelectListItem{ Text="Scooter 3", Value = "3" },
        })
    </p>
    <p>
        <input type="submit" value="Check &raquo;" class="btn btn-default" />
    </p>
}

@if (Model != null)
{
    <table border="1" width="400px">
        <tr>
            <th>
                Scooter
            </th>
            <th>
                User Passport
            </th>
            <th>
                Area
            </th>
        </tr>
        <tr>
            <td>
                Scooter @Model.Scooter.Id.ToString()
            </td>
            <td>
                @Model.Scooter.User.PassportNumber.ToString()
            </td>
            <td>
                Area @Model.LocationAreaId.ToString()
            </td>
        </tr>
    </table>
}

<br />

<address>
    <strong>Code:</strong>   <a href="https://github.com/andreraica/ScooterRental">André Raiça Silva - GitHub</a><br />
</address>

legacy/ScooterRental/ScooterRental/Views/Scooter/Rent.cshtml
@{
    ViewBag.Title = "Rent a Scooter";
}
<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Rent", "Scooter", FormMethod.Post))
{
    <p>
        Passport:
        @Html.TextBox("PassportNumber")
    </p>
    <p>
        Scooter:
        @Html.DropDownList("ScooterId", new List<SelectListItem>
        {
        new SelectListItem{ Text="Scooter 1", Value = "1" },
        new SelectListItem{ Text="Scooter 2", Value = "2" },
        new SelectListItem{ Text="Scooter 3", Value = "3" },
        })
    </p>
    <p>
        <input type="submit" value="Rent &raquo;" class="btn btn-default" />
    </p>
}

<address>
    <strong>Code:</strong>   <a href="https://github.com/andreraica/ScooterRental">André Raiça Silva - GitHub</a><br />
</address>

legacy/ScooterRental/ScooterRental/Views/Scooter/TurnBack.cshtml
@{
    ViewBag.Title = "Turn Back a Scooter";
}
<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("TurnBack", "Scooter", FormMethod.Post))
{
    <p>
        Scooter:
        @Html.DropDownList("ScooterId", new List<SelectListItem>
        {
        new SelectListItem{ Text="Scooter 1", Value = "1" },
        new SelectListItem{ Text="Scooter 2", Value = "2" },
        new SelectListItem{ Text="Scooter 3", Value = "3" },
        })
    </p>
    <p>
        <input type="submit" value="Turn Back &raquo;" class="btn btn-default" />
    </p>
}

<address>
    <strong>Code:</strong>   <a href="https://github.com/andreraica/ScooterRental">André Raiça Silva - GitHub</a><br />
</address>

legacy/ScooterRental/ScooterRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Legacy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Scooter Rental", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2010 - Legacy Scooter Rental</p>
        </footer>
    </div>

    @if (ViewBag.Alert != null)
    {
        <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Alert");
            };
        </script>

    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>